---
- hosts: www

  vars:
    - root_dir: ..
    - my_tomcat_users:
      - {
         name: admin,
         password: admin,
         roles: "admin,admin-gui,manager-gui"
        }

  pre_tasks:
    - debug: msg="Pre tasks section"

  roles:
     - {
         role: "sa-tomcat",
         option_install_java: true,
         tomcat_version: 7,
         tomcat_users: "{{my_tomcat_users}}" 
       }


  tasks:
    - debug: msg="Tasks section"
