---
- hosts: www

  vars:
    - root_dir: ..


  pre_tasks:
    - debug: msg="Pre tasks section"

  roles:
     - {
         role: "sa-tomcat",
         option_install_java: true,
         tomcat_version: 7 
       }


  tasks:
    - debug: msg="Tasks section"
